version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    network_mode: host
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: always

volumes:
  jenkins_home:
